# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'stockSentiments' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for stockSentiments

  # Pods for sign in feature
  pod 'GoogleSignIn'

  # Pods for charts feature
  pod 'Charts'
  pod 'TinyConstraints'

  target 'stockSentimentsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'stockSentimentsUITests' do
    # Pods for testing
  end

end
